//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ffx_framegeneration_api_dll.rc

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#ifndef FFXDLL_FRAMEGENERATION_VERSION_MAJOR
#define FFXDLL_FRAMEGENERATION_VERSION_MAJOR 3
#endif // FFXDLL_FRAMEGENERATION_VERSION_MAJOR

#ifndef FFXDLL_FRAMEGENERATION_VERSION_MINOR
#define FFXDLL_FRAMEGENERATION_VERSION_MINOR 1
#endif // FFXDLL_FRAMEGENERATION_VERSION_MINOR

#ifndef FFXDLL_FRAMEGENERATION_VERSION_PATCH
#define FFXDLL_FRAMEGENERATION_VERSION_PATCH 5
#endif // FFXDLL_FRAMEGENERATION_VERSION_PATCH
