@echo off

echo BuildFSR4Initializers.bat %1 %2 %3

set projectdir=%1
set outputdir=%2
set model=%3

:: Remove all quotes because arguments can contain them
set projectdir=%projectdir:"=%
set outputdir=%outputdir:"=%
set model=%model:"=%

:: Set the absolute path to the FidelityFX directory to avoid issues with long relative path names
pushd %projectdir%..\..\..\
set sdkdir=%cd%
popd

:: Set additional variables with quotes to support paths with spaces
set outdir=%projectdir%%outputdir%ffx_sc_output\
set binFile="%sdkdir%\upscalers\fsr4\internal\shaders\%model%\initializers.bin"
set tempHexFile="%projectdir%%outputdir%ffx_sc_output\temp\%model%_4.txt"

if not exist "%outdir%" (mkdir "%outdir%")
if not exist "%outdir%temp" (mkdir "%outdir%temp")

:: Get the file size
for %%A in (%binFile%) do set initializerFileSize=%%~zA

:: convert the bin file to a hex file
certutil -encodehex -f %binFile% %tempHexFile% 4 >> nul

:: convert it to a cpp file containing the data as a static buffer
(
  echo // auto-generated by BuildFSR4Initializers.bat
  echo extern const unsigned char g_%model%_initializers_data[] = {
  for /F "usebackq tokens=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16 delims= " %%a in (%tempHexFile%) do (echo 0x0%%a,0x0%%b,0x0%%c,0x0%%d,0x0%%e,0x0%%f,0x0%%g,0x0%%h,0x0%%i,0x0%%j,0x0%%k,0x0%%l,0x0%%m,0x0%%n,0x0%%o,0x0%%p,)
  echo };
) > "%outdir%%model%.cpp"

echo "%outdir%%model%.cpp" succesfully created!

:: write the header file
(
  echo // auto-generated by BuildFSR4Initializers.bat
  echo #pragma once
  echo extern const unsigned char g_%model%_initializers_data[];
  echo static const size_t g_%model%_initializers_size = %initializerFileSize%;
) > "%outdir%%model%.h"

echo "%outdir%%model%.h" succesfully created!

::clean up temporary files
del %tempHexFile%

exit /b 0
