#define A WriteOneChar(LettersStart + 0);
#define B WriteOneChar(LettersStart + 1);
#define C WriteOneChar(LettersStart + 2);
#define D WriteOneChar(LettersStart + 3);
#define E WriteOneChar(LettersStart + 4);
#define F WriteOneChar(LettersStart + 5);
#define G WriteOneChar(LettersStart + 6);
#define H WriteOneChar(LettersStart + 7);
#define I WriteOneChar(LettersStart + 8);
#define J WriteOneChar(LettersStart + 9);
#define K WriteOneChar(LettersStart + 10);
#define L WriteOneChar(LettersStart + 11);
#define M WriteOneChar(LettersStart + 12);
#define N WriteOneChar(LettersStart + 13);
#define O WriteOneChar(LettersStart + 14);
#define P WriteOneChar(LettersStart + 15);
#define Q WriteOneChar(LettersStart + 16);
#define R WriteOneChar(LettersStart + 17);
#define S WriteOneChar(LettersStart + 18);
#define T WriteOneChar(LettersStart + 19);
#define U WriteOneChar(LettersStart + 20);
#define V WriteOneChar(LettersStart + 21);
#define W WriteOneChar(LettersStart + 22);
#define X WriteOneChar(LettersStart + 23);
#define Y WriteOneChar(LettersStart + 24);
#define Z WriteOneChar(LettersStart + 25);
#define CL WriteOneChar(SpecialCharColon);
#define NL NewLine();
#define SP AdvanceCursor(1);